#pragma once
#include <iostream>
#include <fstream>
#include <string>
#include <bitset>
#include <vector>
#include <unordered_set>
#include <unordered_map>
#include <QFile>
#include <QBitArray>
#include <QByteArray>
#include <QString>
