#pragma once
#include <iostream>
#include <string>
#include <bitset>
#include <QFile>
#include <QBitArray>
#include <QByteArray>
#include <QString>
#include <QHash>
#include "QtZlib/zlib.h"
