#pragma once
#include <iostream>
#include <string>
#include <bitset>
#include <QFile>
#include <QBitArray>
#include <QByteArray>
#include <QString>
#include <QHash>
#include "QtZlib/zlib.h"
#include <functional>
#include <type_traits>
//#define QT_NO_DEBUG_OUTPUT
#include <QDebug>
#include <QWidget>
#include <QDragEnterEvent>
#include <QMimeData>
#include <QApplication>
#include <QTextEdit>
#include <QDateTime>
#include <QTextStream>
